<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>QRStudio.Presentation</RootNamespace>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\QRStudio.Application\QRStudio.Application.csproj" />
    <ProjectReference Include="..\QRStudio.Domain\QRStudio.Domain.csproj" />
    <ProjectReference Include="..\QRStudio.Infrastructure\QRStudio.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\qr-studio-branding.png" />
  </ItemGroup>
</Project>
